# SPDX-FileCopyrightText: 2025 Sebastian Andersson <sebastian@bittr.nu>
#
# SPDX-License-Identifier: CC0-1.0

version = 1
SPDX-PackageName = "nfc2klipper"
SPDX-PackageSupplier = "Sebastian Andersson <sebastian@bittr.nu>"
SPDX-PackageDownloadLocation = "https://github.com/bofh69/nfc2klipper"

[[annotations]]
path = [
  ".github/**",
  ".gitignore",
  "moonraker-nfc2klipper.cfg",
  "mypy.ini",
  "nfc2klipper.service",
  "nfc2klipper_api.service",
  "nfc2klipper_backend.service",
  "nfc2klipper.cfg",
  "open_print_tag/README",
  "pn532.py.patch",
  "requirements.txt",
  ]
precedence = "aggregate"
SPDX-FileCopyrightText = "$YEAR $NAME <$CONTACT>"
SPDX-License-Identifier = "CC0-1.0"

[[annotations]]
path = [
  "open_print_tag/data/**",
  "open_print_tag/utils/**",
  ]
precedence = "aggregate"
SPDX-FileCopyrightText = "2025 PRUSA RESEARCH A.S."
SPDX-License-Identifier = "MIT"
