# SPDX-FileCopyrightText: 2025 Sebastian Andersson <sebastian@bittr.nu>
#
# SPDX-License-Identifier: CC0-1.0

version = 1
SPDX-PackageName = "nfc2klipper"
SPDX-PackageSupplier = "Sebastian Andersson <sebastian@bittr.nu>"
SPDX-PackageDownloadLocation = "https://github.com/bofh69/nfc2klipper"

[[annotations]]
path = [".github/**", "requirements.txt", ".gitignore", "nfc2klipper.service", "nfc2klipper-config.json5"]
precedence = "aggregate"
SPDX-FileCopyrightText = "$YEAR $NAME <$CONTACT>"
SPDX-License-Identifier = "CC0-1.0"
